import type { Product } from "./types";
import { computeStatus, computeProfitMargin } from "./inventory-utils";

const today = new Date().toISOString();
const futureDate = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
};

function mkVariant(
  size: any,
  qty: number,
  buy: number,
  sell: number,
  threshold = 3,
  preorder = false,
  restock?: string,
) {
  return {
    id: crypto.randomUUID(),
    size,
    stock_quantity: qty,
    low_stock_threshold: threshold,
    buy_price: buy,
    selling_price: sell,
    profit_margin: computeProfitMargin(buy, sell),
    status: computeStatus(qty, threshold, preorder),
    stocked_date: today.slice(0, 10),
    possible_restock_date: restock,
    notes: "",
  } as any;
}

// Fixed pricing rules
const PLAYER = { buy: 800, sell: 1099 };
const FAN = { buy: 700, sell: 899 };
const RETRO = { buy: 950, sell: 1290 };

export const seedProducts: Product[] = [
  {
    id: crypto.randomUUID(),
    product_name: "Argentina 2026 World Cup Version",
    team_country_club: "Argentina",
    player_name: "Messi",
    font_name: "Messi10",
    has_print: true,
    patch_available: true,
    season_year: 2026,
    kit_type: "Home",
    edition_type: "Player Edition",
    manufacturing_type: "Imported",
    source_country: "Thailand",
    supplier_name: "BKK Sports Co.",
    trend_signal: "High",
    trend_reason: "World Cup 2026 hype and Messi demand",
    popularity_score: 95,
    query_count: 18,
    created_at: today,
    variants: [
      mkVariant("M", 8, PLAYER.buy, PLAYER.sell),
      mkVariant("L", 5, PLAYER.buy, PLAYER.sell),
      mkVariant("XL", 2, PLAYER.buy, PLAYER.sell),
    ],
  },
  {
    id: crypto.randomUUID(),
    product_name: "Brazil 2026 WC Away Kit",
    team_country_club: "Brazil",
    player_name: "Neymar",
    font_name: "Neymar10",
    has_print: true,
    patch_available: true,
    season_year: 2026,
    kit_type: "Away",
    edition_type: "Player Edition",
    manufacturing_type: "Imported",
    source_country: "Thailand",
    supplier_name: "BKK Sports Co.",
    trend_signal: "High",
    trend_reason: "Brazil away kit going viral",
    popularity_score: 90,
    query_count: 13,
    created_at: today,
    variants: [
      mkVariant("M", 6, PLAYER.buy, PLAYER.sell),
      mkVariant("L", 4, PLAYER.buy, PLAYER.sell),
      mkVariant("XL", 1, PLAYER.buy, PLAYER.sell, 3),
    ],
  },
  {
    id: crypto.randomUUID(),
    product_name: "Portugal 2026 Away Kit",
    team_country_club: "Portugal",
    player_name: "Ronaldo",
    font_name: "Cristiano7",
    has_print: true,
    patch_available: true,
    season_year: 2026,
    kit_type: "Away",
    edition_type: "Player Edition",
    manufacturing_type: "Imported",
    source_country: "China",
    supplier_name: "GZ Sports Import",
    trend_signal: "Medium",
    trend_reason: "Ronaldo World Cup 2026 interest",
    popularity_score: 82,
    query_count: 9,
    created_at: today,
    variants: [mkVariant("L", 0, PLAYER.buy, PLAYER.sell, 3, true, futureDate(10))],
  },
  {
    id: crypto.randomUUID(),
    product_name: "Barcelona 2026 Home Kit",
    team_country_club: "Barcelona",
    player_name: "Lamine Yamal",
    font_name: "Lamine Yamal19",
    has_print: true,
    patch_available: false,
    season_year: 2026,
    kit_type: "Home",
    edition_type: "Fan Edition",
    manufacturing_type: "Imported",
    source_country: "Thailand",
    supplier_name: "BKK Sports Co.",
    trend_signal: "High",
    trend_reason: "Young star hype and Barcelona demand",
    popularity_score: 84,
    query_count: 11,
    created_at: today,
    variants: [
      mkVariant("S", 6, FAN.buy, FAN.sell),
      mkVariant("M", 5, FAN.buy, FAN.sell),
      mkVariant("L", 4, FAN.buy, FAN.sell),
    ],
  },
  {
    id: crypto.randomUUID(),
    product_name: "Real Madrid 2026 Home Kit",
    team_country_club: "Real Madrid",
    player_name: "Bellingham",
    font_name: "Bellingham5",
    has_print: true,
    patch_available: true,
    season_year: 2026,
    kit_type: "Home",
    edition_type: "Fan Edition",
    manufacturing_type: "Imported",
    source_country: "Thailand",
    supplier_name: "BKK Sports Co.",
    trend_signal: "Medium",
    trend_reason: "Real Madrid fan demand",
    popularity_score: 76,
    query_count: 7,
    created_at: today,
    variants: [
      mkVariant("M", 7, FAN.buy, FAN.sell),
      mkVariant("L", 3, FAN.buy, FAN.sell),
    ],
  },
  {
    id: crypto.randomUUID(),
    product_name: "Argentina 2006 Retro Kit",
    team_country_club: "Argentina",
    player_name: "Messi",
    font_name: "Messi10",
    has_print: true,
    patch_available: false,
    season_year: 2006,
    kit_type: "Retro",
    edition_type: "Retro Kit",
    manufacturing_type: "Imported",
    source_country: "China",
    supplier_name: "GZ Sports Import",
    trend_signal: "High",
    trend_reason: "Argentina retro kit going viral",
    popularity_score: 90,
    query_count: 14,
    created_at: today,
    variants: [
      mkVariant("M", 5, RETRO.buy, RETRO.sell),
      mkVariant("L", 4, RETRO.buy, RETRO.sell),
      mkVariant("XL", 2, RETRO.buy, RETRO.sell),
    ],
  },
  {
    id: crypto.randomUUID(),
    product_name: "Brazil Neymar Retro Kit 2002",
    team_country_club: "Brazil",
    player_name: "Neymar",
    font_name: "Neymar10",
    has_print: true,
    patch_available: false,
    season_year: 2002,
    kit_type: "Retro",
    edition_type: "Retro Kit",
    manufacturing_type: "BD-made",
    source_country: "Bangladesh",
    supplier_name: "Dhaka Jersey Hub",
    trend_signal: "High",
    trend_reason: "Neymar comeback news and Brazil retro demand",
    popularity_score: 88,
    query_count: 12,
    created_at: today,
    variants: [mkVariant("L", 4, RETRO.buy, RETRO.sell)],
  },
  {
    id: crypto.randomUUID(),
    product_name: "Bangladesh National Team Jersey 2026",
    team_country_club: "Bangladesh",
    font_name: "No print",
    has_print: false,
    patch_available: false,
    season_year: 2026,
    kit_type: "Home",
    edition_type: "Fan Edition",
    manufacturing_type: "BD-made",
    source_country: "Bangladesh",
    supplier_name: "Local BD Maker",
    trend_signal: "Medium",
    trend_reason: "Local team pride and seasonal demand",
    popularity_score: 70,
    query_count: 6,
    created_at: today,
    variants: [
      mkVariant("L", 6, FAN.buy, FAN.sell),
      mkVariant("XL", 3, FAN.buy, FAN.sell),
    ],
  },
];
