import type { Product } from "./types";
import { computeStatus, computeProfitMargin } from "./inventory-utils";

const today = new Date().toISOString();
const futureDate = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
};

function mkVariant(
  size: any,
  qty: number,
  buy: number,
  sell: number,
  threshold = 3,
  preorder = false,
  restock?: string,
) {
  return {
    id: crypto.randomUUID(),
    size,
    stock_quantity: qty,
    low_stock_threshold: threshold,
    buy_price: buy,
    selling_price: sell,
    profit_margin: computeProfitMargin(buy, sell),
    status: computeStatus(qty, threshold, preorder),
    stocked_date: today.slice(0, 10),
    possible_restock_date: restock,
    notes: "",
  } as any;
}

export const seedProducts: Product[] = [
  {
    id: crypto.randomUUID(),
    product_name: "Argentina Messi Home Kit 2026",
    team_country_club: "Argentina",
    player_name: "Messi",
    season_year: 2026,
    kit_type: "Home",
    edition_type: "Player Edition",
    manufacturing_type: "Imported",
    source_country: "Thailand",
    supplier_name: "BKK Sports Co.",
    product_image_url: "",
    trend_signal: "High",
    trend_reason: "World Cup 2026 hype and Messi demand",
    popularity_score: 95,
    query_count: 18,
    created_at: today,
    variants: [
      mkVariant("M", 8, 800, 1099),
      mkVariant("L", 5, 800, 1099),
      mkVariant("XL", 2, 800, 1099),
    ],
  },
  {
    id: crypto.randomUUID(),
    product_name: "Brazil Neymar Retro Kit 2002",
    team_country_club: "Brazil",
    player_name: "Neymar",
    season_year: 2002,
    kit_type: "Retro",
    edition_type: "Retro Kit",
    manufacturing_type: "BD-made",
    source_country: "Bangladesh",
    supplier_name: "Dhaka Jersey Hub",
    trend_signal: "High",
    trend_reason: "Neymar comeback news and Brazil retro demand",
    popularity_score: 88,
    query_count: 12,
    created_at: today,
    variants: [mkVariant("L", 4, 950, 1290)],
  },
  {
    id: crypto.randomUUID(),
    product_name: "Portugal Ronaldo Away Kit 2026",
    team_country_club: "Portugal",
    player_name: "Ronaldo",
    season_year: 2026,
    kit_type: "Away",
    edition_type: "Player Edition",
    manufacturing_type: "Imported",
    source_country: "China",
    supplier_name: "GZ Sports Import",
    trend_signal: "Medium",
    trend_reason: "Ronaldo World Cup 2026 interest",
    popularity_score: 82,
    query_count: 9,
    created_at: today,
    variants: [mkVariant("L", 0, 800, 1099, 3, true, futureDate(10))],
  },
  {
    id: crypto.randomUUID(),
    product_name: "Real Madrid Bellingham Home Kit 2026",
    team_country_club: "Real Madrid",
    player_name: "Bellingham",
    season_year: 2026,
    kit_type: "Home",
    edition_type: "Fan Edition",
    manufacturing_type: "Imported",
    source_country: "Thailand",
    supplier_name: "BKK Sports Co.",
    trend_signal: "Medium",
    trend_reason: "Real Madrid fan demand",
    popularity_score: 76,
    query_count: 7,
    created_at: today,
    variants: [mkVariant("M", 7, 700, 899), mkVariant("L", 3, 700, 899)],
  },
  {
    id: crypto.randomUUID(),
    product_name: "Barcelona Lamine Yamal Home Kit 2026",
    team_country_club: "Barcelona",
    player_name: "Lamine Yamal",
    season_year: 2026,
    kit_type: "Home",
    edition_type: "Fan Edition",
    manufacturing_type: "BD-made",
    source_country: "Bangladesh",
    supplier_name: "Dhaka Jersey Hub",
    trend_signal: "High",
    trend_reason: "Young star hype and Barcelona demand",
    popularity_score: 84,
    query_count: 11,
    created_at: today,
    variants: [mkVariant("S", 6, 700, 899), mkVariant("M", 5, 700, 899)],
  },
  {
    id: crypto.randomUUID(),
    product_name: "Bangladesh National Team Jersey 2026",
    team_country_club: "Bangladesh",
    season_year: 2026,
    kit_type: "Home",
    edition_type: "Fan Edition",
    manufacturing_type: "BD-made",
    source_country: "Bangladesh",
    supplier_name: "Local BD Maker",
    trend_signal: "Medium",
    trend_reason: "Local team pride and seasonal demand",
    popularity_score: 70,
    query_count: 6,
    created_at: today,
    variants: [mkVariant("L", 6, 700, 899), mkVariant("XL", 3, 700, 899)],
  },
  {
    id: crypto.randomUUID(),
    product_name: "Argentina 2006 Retro Kit",
    team_country_club: "Argentina",
    player_name: "Messi",
    season_year: 2006,
    kit_type: "Retro",
    edition_type: "Retro Kit",
    manufacturing_type: "Imported",
    source_country: "China",
    supplier_name: "GZ Sports Import",
    trend_signal: "High",
    trend_reason: "Argentina retro kit going viral",
    popularity_score: 90,
    query_count: 14,
    created_at: today,
    variants: [
      mkVariant("M", 5, 950, 1290),
      mkVariant("L", 4, 950, 1290),
      mkVariant("XL", 2, 950, 1290),
    ],
  },
];
